// Generated by PeakRDL-etana - A free and open-source SystemVerilog generator
//  https://github.com/daxzio/PeakRDL-etana

`timescale 1ns / 1ps

module regblock #(
        parameter ID_WIDTH = 1
    ) (
        input wire clk,
        input wire rst,

        input wire s_obi_req,
        output logic s_obi_gnt,
        input wire [7:0] s_obi_addr,
        input wire s_obi_we,
        input wire [3:0] s_obi_be,
        input wire [31:0] s_obi_wdata,
        input wire [ID_WIDTH-1:0] s_obi_aid,
        output logic s_obi_rvalid,
        input wire s_obi_rready,
        output logic [31:0] s_obi_rdata,
        output logic s_obi_err,
        output logic [ID_WIDTH-1:0] s_obi_rid,

        output logic [7:0] hwif_out_ext_mem_addr,
        output logic hwif_out_ext_mem_req,
        input logic [31:0] hwif_in_ext_mem_rd_data,
        input logic hwif_in_ext_mem_rd_ack,
        input logic hwif_in_ext_mem_wr_ack,
        output logic hwif_out_ext_mem_req_is_wr,
        output logic [31:0] hwif_out_ext_mem_wr_data,
        output logic [31:0] hwif_out_ext_mem_wr_biten
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [7:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;


    // Two-stage OBI pipeline: accept -> one-cycle cpuif_req pulse -> ack
    // (combo or delayed). cpuif_req is never held, so SW strobes and external
    // hwif requests are not re-issued. Delayed ack is skidded in exec_held if R
    // is stalled.
    //
    // Combo-ack registers (internal FFs): rvalid is forwarded on the ack cycle,
    // so A (req&&gnt) is followed by R on the next clock. rsp_valid only holds
    // the beat when rready is low. OBI R-5: rvalid is not combinational from
    // the same-cycle accept (cpuif_req is registered).
    logic [31:0] rsp_rdata_q;
    logic rsp_err_q;
    logic rsp_valid;
    logic [$bits(s_obi_rid)-1:0] rid_q;
    logic [$bits(s_obi_rid)-1:0] rid_inflight;

    logic exec_valid;
    logic exec_held;
    logic [31:0] exec_rdata_q;
    logic exec_err_q;
    logic [$bits(s_obi_rid)-1:0] exec_rid_q;

    logic cpuif_ack;
    logic obi_accept;
    logic obi_rdone;
    logic rsp_take;
    logic exec_result_valid;
    logic presenting_live;
    assign cpuif_ack = cpuif_rd_ack | cpuif_wr_ack;
    assign exec_result_valid = exec_held | (exec_valid & cpuif_ack);
    assign presenting_live = exec_result_valid & ~rsp_valid;
    assign s_obi_rvalid = rsp_valid | presenting_live;
    assign s_obi_rdata = rsp_valid ? rsp_rdata_q : (exec_held ? exec_rdata_q : cpuif_rd_data);
    assign s_obi_err = rsp_valid ? rsp_err_q : (exec_held ? exec_err_q : (cpuif_rd_err | cpuif_wr_err));
    assign s_obi_rid = rsp_valid ? rid_q : (exec_held ? exec_rid_q : rid_inflight);
    assign obi_rdone = s_obi_rvalid & s_obi_rready;
    assign rsp_take = exec_result_valid & (~rsp_valid | s_obi_rready);
    assign s_obi_gnt = ~rst & (~exec_valid | rsp_take)
        // Early read strobe shares the 1-port hwif with the registered write pulse.
        // Do not accept a read on the same cycle a write is issued to the SRAM.
        & ~(cpuif_req & cpuif_req_is_wr & ~s_obi_we);
    assign obi_accept = s_obi_req & s_obi_gnt;

    always_ff @(posedge clk) begin
        if (rst) begin
            rsp_valid <= 1'b0;
            rsp_rdata_q <= '0;
            rsp_err_q <= 1'b0;
            rid_q <= '0;
            rid_inflight <= '0;
            exec_valid <= 1'b0;
            exec_held <= 1'b0;
            exec_rdata_q <= '0;
            exec_err_q <= '0;
            exec_rid_q <= '0;

            cpuif_req <= '0;
            cpuif_req_is_wr <= '0;
            cpuif_addr <= '0;
            cpuif_wr_data <= '0;
            cpuif_wr_biten <= '0;
        end else begin
            cpuif_req <= obi_accept;

            if (obi_accept) begin
                exec_valid <= 1'b1;
                cpuif_req_is_wr <= s_obi_we;
                cpuif_addr <= { s_obi_addr[7:2], 2'b0};
                cpuif_wr_data <= s_obi_wdata;
                rid_inflight <= s_obi_aid;
                for (int i = 0; i < 4; i++) begin
                    cpuif_wr_biten[i*8 +: 8] <= {8{ s_obi_be[i] }};
                end
            end else if (rsp_take) begin
                exec_valid <= 1'b0;
            end

            if (rsp_take) begin
                exec_held <= 1'b0;
            end else if (exec_valid && cpuif_ack && !exec_held) begin
                exec_held <= 1'b1;
                exec_rdata_q <= cpuif_rd_data;
                exec_err_q <= cpuif_rd_err | cpuif_wr_err;
                exec_rid_q <= rid_inflight;
            end

            if (rsp_valid) begin
                if (s_obi_rready) begin
                    if (exec_result_valid) begin
                        rsp_rdata_q <= exec_held ? exec_rdata_q : cpuif_rd_data;
                        rsp_err_q <= exec_held ? exec_err_q : (cpuif_rd_err | cpuif_wr_err);
                        rid_q <= exec_held ? exec_rid_q : rid_inflight;
                    end else begin
                        rsp_valid <= 1'b0;
                    end
                end
            end else if (presenting_live && !s_obi_rready) begin
                rsp_valid <= 1'b1;
                rsp_rdata_q <= exec_held ? exec_rdata_q : cpuif_rd_data;
                rsp_err_q <= exec_held ? exec_err_q : (cpuif_rd_err | cpuif_wr_err);
                rid_q <= exec_held ? exec_rid_q : rid_inflight;
            end
        end
    end
    // Early (SETUP-phase) request channel.  Un-registered view of the CPUIF
    // request, so external blocks with a registered read port can start one
    // cycle earlier.  Valid only while the CPUIF is idle.
    logic cpuif_early_req;
    logic cpuif_early_req_is_wr;
    logic [7:0] cpuif_early_addr;

    assign cpuif_early_req = s_obi_req & ~s_obi_we & ~(cpuif_req & cpuif_req_is_wr) & (~exec_valid | (cpuif_req & ~cpuif_req_is_wr) | (exec_held & (~rsp_valid | s_obi_rready)));
    assign cpuif_early_req_is_wr = s_obi_we;
    assign cpuif_early_addr = {s_obi_addr[7:2], 2'b0};

    logic cpuif_req_masked;
    logic external_req;
    logic external_pending;
    logic external_wr_ack;
    logic external_rd_ack;
//     always_ff @(posedge clk) begin
    always @(posedge clk) begin
        if(rst) begin
            external_pending <= '0;
        end else begin
            if(external_req & ~external_wr_ack & ~external_rd_ack) external_pending <= '1;
            else if(external_wr_ack | external_rd_ack) external_pending <= '0;
            `ifndef SYNTHESIS
                assert_bad_ext_wr_ack: assert($isunknown(external_wr_ack) || !external_wr_ack || (external_pending | external_req))
                    else $error("An external wr_ack strobe was asserted when no external request was active");
                assert_bad_ext_rd_ack: assert($isunknown(external_rd_ack) || !external_rd_ack || (external_pending | external_req))
                    else $error("An external rd_ack strobe was asserted when no external request was active");
            `endif
        end
    end

    // Read & write latencies are balanced. Stalls not required
    // except if external
    assign cpuif_req_stall_rd = external_pending;
    assign cpuif_req_stall_wr = external_pending;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    logic decoded_reg_strb_ext_mem;
    logic decoded_early_strb_ext_mem;
    logic decoded_strb_is_external;

    logic [7:0] decoded_addr;

    logic decoded_req;
    logic decoded_req_is_wr;
    /* verilator lint_off UNUSEDSIGNAL */
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;
    /* verilator lint_on UNUSEDSIGNAL */

    always @(*) begin
        /* verilator lint_off UNUSEDSIGNAL */
        integer next_cpuif_addr;
        /* verilator lint_on UNUSEDSIGNAL */
        logic is_external;
        logic is_early_external;
        is_external = '0;
        is_early_external = '0;
        decoded_reg_strb_ext_mem = cpuif_req_masked;
        is_external |= cpuif_req_masked;
        decoded_early_strb_ext_mem = cpuif_early_req & ~cpuif_early_req_is_wr;
        is_early_external |= cpuif_early_req & ~cpuif_early_req_is_wr;
        decoded_strb_is_external = is_external;
        external_req = is_external | is_early_external;
    end

    // Pass down signals to next stage
    assign decoded_addr = cpuif_addr;

    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;


    //--------------------------------------------------------------------------
    // Field storage declarations
    //--------------------------------------------------------------------------

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------

    // early_external_read: read req is a single-cycle SETUP-phase strobe; rd_ack/rd_data
    // must be valid exactly one cycle later. Zero-latency slaves will deadlock.
    assign hwif_out_ext_mem_addr = decoded_early_strb_ext_mem ? cpuif_early_addr[7:0]
                                            : decoded_addr[7:0];
    assign hwif_out_ext_mem_req = decoded_early_strb_ext_mem | (decoded_reg_strb_ext_mem & decoded_req_is_wr);
    assign hwif_out_ext_mem_req_is_wr = decoded_reg_strb_ext_mem & decoded_req_is_wr;
    assign hwif_out_ext_mem_wr_data = decoded_wr_data;
    assign hwif_out_ext_mem_wr_biten = decoded_wr_biten;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    always @(*) begin
        logic wr_ack;
        wr_ack = '0;
        wr_ack |= hwif_in_ext_mem_wr_ack;
        external_wr_ack = wr_ack;
    end
    assign cpuif_wr_ack = external_wr_ack | (decoded_req & decoded_req_is_wr & ~decoded_strb_is_external);
    // Write error: decoded (bad addr/rw) or external mem wr_err from err_support
    assign cpuif_wr_err = '0;

//--------------------------------------------------------------------------
// Readback
//--------------------------------------------------------------------------
    logic readback_external_rd_ack;
    logic readback_external_rd_ack_c;
    always @(*) begin
        logic rd_ack;
        rd_ack = '0;
        rd_ack |= hwif_in_ext_mem_rd_ack;
        readback_external_rd_ack_c = rd_ack;
    end

    assign readback_external_rd_ack = readback_external_rd_ack_c;

    logic readback_external_rd_err;
    assign readback_external_rd_err = '0;

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;
always @(*) begin
        // Icarus limitation: does not support overriding variable lifetime (automatic).
        // A regular block-local temp is sufficient here since logic is purely combinational.
        logic [31:0] readback_data_var;
        readback_data_var = '0;
        readback_data_var = hwif_in_ext_mem_rd_data;
        readback_data = readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr & ~decoded_strb_is_external;
        readback_err = '0;
    end

    assign external_rd_ack = readback_external_rd_ack;
    assign cpuif_rd_ack = readback_done | readback_external_rd_ack;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err | readback_external_rd_err;
endmodule
