// Generated by PeakRDL-etana - A free and open-source SystemVerilog generator
//  https://github.com/daxzio/PeakRDL-etana

`timescale 1ns / 1ps

module regblock #(
        parameter ID_WIDTH = 1
    ) (
        input wire clk,
        input wire rst,

        input wire s_obi_req,
        output logic s_obi_gnt,
        input wire [7:0] s_obi_addr,
        input wire s_obi_we,
        input wire [3:0] s_obi_be,
        input wire [31:0] s_obi_wdata,
        input wire [ID_WIDTH-1:0] s_obi_aid,
        output logic s_obi_rvalid,
        input wire s_obi_rready,
        output logic [31:0] s_obi_rdata,
        output logic s_obi_err,
        output logic [ID_WIDTH-1:0] s_obi_rid,

        output logic [7:0] hwif_out_ext_mem_addr,
        output logic hwif_out_ext_mem_req,
        input logic [31:0] hwif_in_ext_mem_rd_data,
        input logic hwif_in_ext_mem_rd_ack,
        input logic hwif_in_ext_mem_wr_ack,
        output logic hwif_out_ext_mem_req_is_wr,
        output logic [31:0] hwif_out_ext_mem_wr_data,
        output logic [31:0] hwif_out_ext_mem_wr_biten
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [7:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;


    // State & holding regs
    logic is_active; // A request is being served (not yet fully responded)
    logic rsp_pending; // response stalled: manager was not ready when it completed
    logic [31:0] rsp_rdata_q;
    logic rsp_err_q;
    logic [$bits(s_obi_rid)-1:0] rid_q;

    // The response is presented in the same cycle the regblock acknowledges, so a
    // transaction costs no more than the interface minimum. The rsp_* registers
    // only take over when the manager stalls the R channel with rready low.
    // Gating on is_active is what keeps this legal: is_active is set on the edge the
    // address phase completes, so rvalid can only rise in a later cycle (OBI R-5).
    logic rsp_ack;
    assign rsp_ack = is_active & ~rsp_pending & (cpuif_rd_ack | cpuif_wr_ack);

    // Back-to-back accept: when the R handshake completes and the manager already
    // has the next req asserted, take the new address phase in the same cycle
    // instead of forcing a one-cycle bubble (processor-style issue while !gnt).
    logic obi_finish;
    logic obi_accept;
    assign obi_finish = (rsp_pending | rsp_ack) & s_obi_rready;
    assign obi_accept = s_obi_req & (~is_active | obi_finish);

    // Latch AID on accept to echo back the response
    always_ff @(posedge clk) begin
        if (rst) begin
            is_active <= 1'b0;
            rsp_pending <= 1'b0;
            rsp_rdata_q <= '0;
            rsp_err_q <= 1'b0;
            rid_q <= '0;

            cpuif_req <= '0;
            cpuif_req_is_wr <= '0;
            cpuif_addr <= '0;
            cpuif_wr_data <= '0;
            cpuif_wr_biten <= '0;
        end else begin
            // defaults
            cpuif_req <= 1'b0;

            if (obi_accept) begin
                is_active <= 1'b1;
                cpuif_req <= 1'b1;
                cpuif_req_is_wr <= s_obi_we;
                cpuif_addr <= { s_obi_addr[7:2], 2'b0};
                cpuif_wr_data <= s_obi_wdata;
                rid_q <= s_obi_aid;
                for (int i = 0; i < 4; i++) begin
                    cpuif_wr_biten[i*8 +: 8] <= {8{ s_obi_be[i] }};
                end
            end else if (obi_finish) begin
                is_active <= 1'b0;
            end

            // Capture the response only if the manager cannot accept it this cycle
            if (rsp_ack && !s_obi_rready) begin
                rsp_pending <= 1'b1;
                rsp_rdata_q <= cpuif_rd_data;
                rsp_err_q <= cpuif_rd_err | cpuif_wr_err;
                // NOTE: Keep 'is_active' asserted until the external R handshake completes
            end

            // Complete external R-channel handshake only if manager ready.
            // rvalid itself does not depend on rready (R-21.3).
            if (obi_finish) begin
                rsp_pending <= 1'b0;
            end
        end
    end

    // R-channel outputs: forwarded from the regblock on the ack cycle, then held
    // stable from the rsp_* registers for as long as the manager stalls.
    assign s_obi_rvalid = rsp_pending | rsp_ack;
    assign s_obi_rdata = rsp_pending ? rsp_rdata_q : cpuif_rd_data;
    assign s_obi_err = rsp_pending ? rsp_err_q : (cpuif_rd_err | cpuif_wr_err);
    assign s_obi_rid = rid_q;

    // A-channel grant. Assert only when a req&&gnt beat would be accepted:
    // idle, or completing the R handshake this cycle (back-to-back accept).
    assign s_obi_gnt = ~is_active | obi_finish;

    logic cpuif_req_masked;
    logic external_req;
    logic external_pending;
    logic external_wr_ack;
    logic external_rd_ack;
//     always_ff @(posedge clk) begin
    always @(posedge clk) begin
        if(rst) begin
            external_pending <= '0;
        end else begin
            if(external_req & ~external_wr_ack & ~external_rd_ack) external_pending <= '1;
            else if(external_wr_ack | external_rd_ack) external_pending <= '0;
            `ifndef SYNTHESIS
                assert_bad_ext_wr_ack: assert($isunknown(external_wr_ack) || !external_wr_ack || (external_pending | external_req))
                    else $error("An external wr_ack strobe was asserted when no external request was active");
                assert_bad_ext_rd_ack: assert($isunknown(external_rd_ack) || !external_rd_ack || (external_pending | external_req))
                    else $error("An external rd_ack strobe was asserted when no external request was active");
            `endif
        end
    end

    // Read & write latencies are balanced. Stalls not required
    // except if external
    assign cpuif_req_stall_rd = external_pending;
    assign cpuif_req_stall_wr = external_pending;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    logic decoded_reg_strb_ext_mem;
    logic decoded_strb_is_external;

    logic [7:0] decoded_addr;

    logic decoded_req;
    logic decoded_req_is_wr;
    /* verilator lint_off UNUSEDSIGNAL */
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;
    /* verilator lint_on UNUSEDSIGNAL */

    always @(*) begin
        /* verilator lint_off UNUSEDSIGNAL */
        integer next_cpuif_addr;
        /* verilator lint_on UNUSEDSIGNAL */
        logic is_external;
        is_external = '0;
        decoded_reg_strb_ext_mem = cpuif_req_masked;
        is_external |= cpuif_req_masked;
        decoded_strb_is_external = is_external;
        external_req = is_external;
    end

    // Pass down signals to next stage
    assign decoded_addr = cpuif_addr;

    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;


    //--------------------------------------------------------------------------
    // Field storage declarations
    //--------------------------------------------------------------------------

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------

    assign hwif_out_ext_mem_addr = decoded_addr[7:0];
    assign hwif_out_ext_mem_req = decoded_reg_strb_ext_mem;
    assign hwif_out_ext_mem_req_is_wr = decoded_reg_strb_ext_mem & decoded_req_is_wr;
    assign hwif_out_ext_mem_wr_data = decoded_wr_data;
    assign hwif_out_ext_mem_wr_biten = decoded_wr_biten;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    always @(*) begin
        logic wr_ack;
        wr_ack = '0;
        wr_ack |= hwif_in_ext_mem_wr_ack;
        external_wr_ack = wr_ack;
    end
    assign cpuif_wr_ack = external_wr_ack | (decoded_req & decoded_req_is_wr & ~decoded_strb_is_external);
    // Write error: decoded (bad addr/rw) or external mem wr_err from err_support
    assign cpuif_wr_err = '0;

//--------------------------------------------------------------------------
// Readback
//--------------------------------------------------------------------------
    logic readback_external_rd_ack;
    logic readback_external_rd_ack_c;
    always @(*) begin
        logic rd_ack;
        rd_ack = '0;
        rd_ack |= hwif_in_ext_mem_rd_ack;
        readback_external_rd_ack_c = rd_ack;
    end

    assign readback_external_rd_ack = readback_external_rd_ack_c;

    logic readback_external_rd_err;
    assign readback_external_rd_err = '0;

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;
always @(*) begin
        // Icarus limitation: does not support overriding variable lifetime (automatic).
        // A regular block-local temp is sufficient here since logic is purely combinational.
        logic [31:0] readback_data_var;
        readback_data_var = '0;
        readback_data_var = hwif_in_ext_mem_rd_data;
        readback_data = readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr & ~decoded_strb_is_external;
        readback_err = '0;
    end

    assign external_rd_ack = readback_external_rd_ack;
    assign cpuif_rd_ack = readback_done | readback_external_rd_ack;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err | readback_external_rd_err;
endmodule
