// Generated by PeakRDL-etana - A free and open-source SystemVerilog generator
//  https://github.com/daxzio/PeakRDL-etana

`timescale 1ns / 1ps

module regblock #(
        parameter ID_WIDTH = 1
    ) (
        input wire clk,
        input wire rst,

        input wire s_obi_req,
        output logic s_obi_gnt,
        input wire [3:0] s_obi_addr,
        input wire s_obi_we,
        input wire [3:0] s_obi_be,
        input wire [31:0] s_obi_wdata,
        input wire [ID_WIDTH-1:0] s_obi_aid,
        output logic s_obi_rvalid,
        input wire s_obi_rready,
        output logic [31:0] s_obi_rdata,
        output logic s_obi_err,
        output logic [ID_WIDTH-1:0] s_obi_rid,

        output logic [31:0] hwif_out_r_w_f
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [3:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;


    // State & holding regs
    logic is_active; // A request is being served (not yet fully responded)
    logic rsp_pending; // response stalled: manager was not ready when it completed
    logic [31:0] rsp_rdata_q;
    logic rsp_err_q;
    logic [$bits(s_obi_rid)-1:0] rid_q;

    // The response is presented in the same cycle the regblock acknowledges, so a
    // transaction costs no more than the interface minimum. The rsp_* registers
    // only take over when the manager stalls the R channel with rready low.
    // Gating on is_active is what keeps this legal: is_active is set on the edge the
    // address phase completes, so rvalid can only rise in a later cycle (OBI R-5).
    logic rsp_ack;
    assign rsp_ack = is_active & ~rsp_pending & (cpuif_rd_ack | cpuif_wr_ack);

    // Back-to-back accept: when the R handshake completes and the manager already
    // has the next req asserted, take the new address phase in the same cycle
    // instead of forcing a one-cycle bubble (processor-style issue while !gnt).
    logic obi_finish;
    logic obi_accept;
    assign obi_finish = (rsp_pending | rsp_ack) & s_obi_rready;
    assign obi_accept = s_obi_req & (~is_active | obi_finish);

    // Latch AID on accept to echo back the response
    always_ff @(posedge clk) begin
        if (rst) begin
            is_active <= 1'b0;
            rsp_pending <= 1'b0;
            rsp_rdata_q <= '0;
            rsp_err_q <= 1'b0;
            rid_q <= '0;

            cpuif_req <= '0;
            cpuif_req_is_wr <= '0;
            cpuif_addr <= '0;
            cpuif_wr_data <= '0;
            cpuif_wr_biten <= '0;
        end else begin
            // defaults
            cpuif_req <= 1'b0;

            if (obi_accept) begin
                is_active <= 1'b1;
                cpuif_req <= 1'b1;
                cpuif_req_is_wr <= s_obi_we;
                cpuif_addr <= { s_obi_addr[3:2], 2'b0};
                cpuif_wr_data <= s_obi_wdata;
                rid_q <= s_obi_aid;
                for (int i = 0; i < 4; i++) begin
                    cpuif_wr_biten[i*8 +: 8] <= {8{ s_obi_be[i] }};
                end
            end else if (obi_finish) begin
                is_active <= 1'b0;
            end

            // Capture the response only if the manager cannot accept it this cycle
            if (rsp_ack && !s_obi_rready) begin
                rsp_pending <= 1'b1;
                rsp_rdata_q <= cpuif_rd_data;
                rsp_err_q <= cpuif_rd_err | cpuif_wr_err;
                // NOTE: Keep 'is_active' asserted until the external R handshake completes
            end

            // Complete external R-channel handshake only if manager ready.
            // rvalid itself does not depend on rready (R-21.3).
            if (obi_finish) begin
                rsp_pending <= 1'b0;
            end
        end
    end

    // R-channel outputs: forwarded from the regblock on the ack cycle, then held
    // stable from the rsp_* registers for as long as the manager stalls.
    assign s_obi_rvalid = rsp_pending | rsp_ack;
    assign s_obi_rdata = rsp_pending ? rsp_rdata_q : cpuif_rd_data;
    assign s_obi_err = rsp_pending ? rsp_err_q : (cpuif_rd_err | cpuif_wr_err);
    assign s_obi_rid = rid_q;

    // A-channel grant. Assert only when a req&&gnt beat would be accepted:
    // idle, or completing the R handshake this cycle (back-to-back accept).
    assign s_obi_gnt = ~is_active | obi_finish;

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    logic decoded_reg_strb_r_rw;
    logic decoded_reg_strb_r_r;
    logic decoded_reg_strb_r_w;
    logic decoded_err;

    logic decoded_req;
    logic decoded_req_is_wr;
    /* verilator lint_off UNUSEDSIGNAL */
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;
    /* verilator lint_on UNUSEDSIGNAL */

    always @(*) begin
        /* verilator lint_off UNUSEDSIGNAL */
        integer next_cpuif_addr;
        /* verilator lint_on UNUSEDSIGNAL */
        logic is_valid_addr;
        logic is_valid_rw;
        is_valid_addr = '0;
        is_valid_rw = '0;
        decoded_reg_strb_r_rw = cpuif_req_masked & (cpuif_addr == 4'h0);
        is_valid_addr |= cpuif_req_masked & (cpuif_addr == 4'h0);
        is_valid_rw |= cpuif_req_masked & (cpuif_addr == 4'h0);
        decoded_reg_strb_r_r = cpuif_req_masked & (cpuif_addr == 4'h4) & !cpuif_req_is_wr;
        is_valid_addr |= cpuif_req_masked & (cpuif_addr == 4'h4);
        is_valid_rw |= cpuif_req_masked & (cpuif_addr == 4'h4) & !cpuif_req_is_wr;
        decoded_reg_strb_r_w = cpuif_req_masked & (cpuif_addr == 4'h8) & cpuif_req_is_wr;
        is_valid_addr |= cpuif_req_masked & (cpuif_addr == 4'h8);
        is_valid_rw |= cpuif_req_masked & (cpuif_addr == 4'h8) & cpuif_req_is_wr;
        decoded_err = (~is_valid_addr | (is_valid_addr & ~is_valid_rw)) & decoded_req;
    end

    // Pass down signals to next stage
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;


    //--------------------------------------------------------------------------
    // Field storage declarations
    //--------------------------------------------------------------------------

    // Field: regblock.r_rw.f
    logic [31:0] field_storage_r_rw_f_value;
    logic [31:0] field_combo_r_rw_f_next;
    logic field_combo_r_rw_f_load_next;
    // Field: regblock.r_w.f
    logic [31:0] field_storage_r_w_f_value;
    logic [31:0] field_combo_r_w_f_next;
    logic field_combo_r_w_f_load_next;
    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    always @(*) begin
        logic [31:0] next_c;
        logic load_next_c;
        next_c = field_storage_r_rw_f_value;
        load_next_c = '0;
        if(decoded_reg_strb_r_rw && decoded_req_is_wr) begin // SW write
            next_c = (field_storage_r_rw_f_value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo_r_rw_f_next = next_c;
        field_combo_r_rw_f_load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage_r_rw_f_value <= 32'h28;
        end else if(field_combo_r_rw_f_load_next) begin
            field_storage_r_rw_f_value <= field_combo_r_rw_f_next;
        end
    end
    always @(*) begin
        logic [31:0] next_c;
        logic load_next_c;
        next_c = field_storage_r_w_f_value;
        load_next_c = '0;
        if(decoded_reg_strb_r_w && decoded_req_is_wr) begin // SW write
            next_c = (field_storage_r_w_f_value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo_r_w_f_next = next_c;
        field_combo_r_w_f_load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage_r_w_f_value <= 32'h64;
        end else if(field_combo_r_w_f_load_next) begin
            field_storage_r_w_f_value <= field_combo_r_w_f_next;
        end
    end
    assign hwif_out_r_w_f = field_storage_r_w_f_value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Write error: decoded (bad addr/rw) or external mem wr_err from err_support
    assign cpuif_wr_err = decoded_err;

//--------------------------------------------------------------------------
// Readback
//--------------------------------------------------------------------------
    logic readback_external_rd_ack;
    assign readback_external_rd_ack = 0;

    logic readback_external_rd_err;
    assign readback_external_rd_err = '0;
    // Readback mux address
    // When external accesses are present, hold address stable so readback mux can
    // continue selecting the correct external data while waiting for rd_ack.
    logic [3:0] rd_mux_addr;
    assign rd_mux_addr = cpuif_addr;

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;
always @(*) begin
        // Icarus limitation: does not support overriding variable lifetime (automatic).
        // A regular block-local temp is sufficient here since logic is purely combinational.
        logic [31:0] readback_data_var;
        readback_data_var = '0;
        if(rd_mux_addr == 4'h0) begin
            readback_data_var[31:0] = field_storage_r_rw_f_value;
        end
        if(rd_mux_addr == 4'h4) begin
            readback_data_var[31:0] = 32'h50;
        end
        readback_data = readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = decoded_err;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err | readback_external_rd_err;
endmodule
