# package information
[metadata]
name = cocotbext_obi
version = attr: cocotbext.obi.version.__version__
description = OBI (Open Bus Interface) modules for cocotb
keywords = obi, cocotb, openhw, risc-v
author = Dave Keeshan
author_email = dave.keeshan@daxzio.com
license = MIT
url = https://github.com/daxzio/cocotbext-obi
project_urls =
    Bug Tracker = https://github.com/daxzio/cocotbext-obi/issues
    Source Code = https://github.com/daxzio/cocotbext-obi
download_url = https://github.com/daxzio/cocotbext-obi/tarball/master
long_description = file: README.md
long_description_content_type = text/markdown
platforms = any
classifiers =
    Development Status :: 4 - Beta
    Framework :: cocotb
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13
    Programming Language :: Python :: 3.14
    Topic :: Scientific/Engineering :: Electronic Design Automation (EDA)

[options]
packages = find_namespace:
python_requires = >=3.8
install_requires =
    cocotb>=1.9.0

[options.extras_require]
test =
    pytest
    pytest-xdist
interface =
    cocotbext-interface

[options.packages.find]
include = cocotbext.*

# pytest configuration
[tool:pytest]
testpaths =
    tests
python_files =
    test_*.py
norecursedirs =
    test_*
    sim_build
addopts =
    --import-mode importlib
    -v

# flake8 configuration
[flake8]
exclude = .git .tox *.egg build
max-line-length = 119
ignore =
    E123 # closing bracket does not match indentation of opening bracket's line
    E126 # continuation line over-indented for hanging indent
    E128 # continuation line under-indented for visual indent
    E221 # multiple spaces before operator
    E226 # missing whitespace around arithmetic operator
    E241 # multiple spaces after ','
    E262 # inline comment should start with '# '
    W503 # line break before binary operator
    W504 # line break after binary operator
per-file-ignores =
    __init__.py:F401

