SIM?=icarus
TOPLEVEL_LANG=verilog
WORK_BASE?=..

TOPLEVEL = regblock
MODULE = test_dut

INT_VERILOG_SOURCES += \
	../test_basic/regblock.sv \

COCOTB_SOURCES = \

include ${WORK_BASE}/rtlflo/cocotb_helper.mak
